# https://cert-manager.io/docs/configuration/selfsigned/
{{- if not .Values.certificates.issuer.name }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "wazuh.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
  subject: #! What to add here? TODO
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "wazuh.fullname" . }}-root-ca
spec:
  isCA: true
  secretName: root-secret
  commonName: root-ca
  subject:
    organizations:
      - {{ .Values.certificates.subject.organization }}
    countries:
      - {{ .Values.certificates.subject.country }}
    localities:
      - {{ .Values.certificates.subject.locality }}
  privateKey:
    algorithm: RSA
    size: 2048
  duration: 87600h # 3650d
  issuerRef:
    name: {{ include "wazuh.fullname" . }}-selfsigned-issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "wazuh.fullname" . }}-ca-issuer
spec:
  ca:
    secretName: root-secret
{{- end -}}
