apiVersion: v1
kind: Service
metadata:
  # Name is only "wazuh" because of Certificates commonName
  name: wazuh
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "wazuh.fullname" . }}-manager
    node-type: master
  annotations:
    {{- toYaml .Values.wazuh.master.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.wazuh.master.service.type }}
  ports:
  {{- range .Values.wazuh.master.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if (and (eq .Values.wazuh.master.service.type "NodePort") (not (empty .nodePort))) }}
      nodePort: {{ .nodePort }}
      {{- end }}
  {{- end }}
  selector:
    app: {{ include "wazuh.fullname" . }}-manager
    node-type: master
  type: {{ .Values.wazuh.master.service.type }}
