apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "wazuh.fullname" . }}-ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ include "wazuh.fullname" . }}-root-secret
