{{- if .Values.wazuh.enabled }}
  {{- if not .Values.wazuh.keyExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-cluster-key
  namespace: {{ .Release.Namespace }}
data:
  key: {{ .Values.wazuh.key | b64enc }}
  {{- end }}
{{- end }}
