{{- if .Values.wazuh.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wazuh.manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "wazuh.fullname" . }}-manager
    app.kubernetes.io/component: manager
  {{- with .Values.wazuh.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.wazuh.serviceAccount.automountServiceAccountToken | default true }}
{{- end }}
