{{- if .Values.indexer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.indexer.fullname" . }}-indexer-nodes
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "wazuh.indexer.fullname" . }}-indexer
  annotations:
    {{- toYaml .Values.indexer.service.annotations | nindent 4 }}
spec:
  clusterIP: None
  {{- if .Values.global.dualStack.enabled }}
  {{- if .Values.global.dualStack.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.global.dualStack.ipFamilyPolicy }}
  {{- end }}
  {{- if .Values.global.dualStack.ipFamilies }}
  ipFamilies:
    {{- toYaml .Values.global.dualStack.ipFamilies | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - name: indexer-nodes
      port: {{ .Values.indexer.service.nodes }}
      targetPort: {{ .Values.indexer.service.nodes }}
  selector:
    app: {{ include "wazuh.indexer.fullname" . }}-indexer
{{- end }}
