{{- if .Values.indexer.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "wazuh.indexer.fullname" . }}-indexer
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "wazuh.indexer.fullname" . }}-indexer
  annotations:
    {{- toYaml .Values.indexer.annotations | nindent 4 }}
spec:
  {{- with .Values.indexer.extraSpec.statefulSet }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  serviceName: {{ include "wazuh.indexer.fullname" . }}-indexer-nodes
  replicas: {{ .Values.indexer.replicas }}
  updateStrategy:
    type: {{ .Values.indexer.updateStrategy }}
  selector:
    matchLabels:
      app: {{ include "wazuh.indexer.fullname" . }}-indexer
  template:
    metadata:
      labels:
        app: {{ include "wazuh.indexer.fullname" . }}-indexer
      annotations:
        {{- if .Values.autoreload.enabled }}
        checksum/configmap: {{ include (print $.Template.BasePath "/indexer/configmap.yaml") . | sha256sum }}
        checksum/certificate: {{ include (print $.Template.BasePath "/certs/certificate.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.indexer.annotations }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.indexer.extraSpec.pod }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.indexer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if and .Values.indexer.sysctlImage.enabled }}
      initContainers:
        ## Image that performs the sysctl operation to modify Kernel settings (needed sometimes to avoid boot errors)
        - name: sysctl
          image: "{{ .Values.indexer.sysctlImage.images.repository }}:{{ .Values.indexer.sysctlImage.images.tag }}"
          imagePullPolicy: {{ .Values.indexer.images.pullPolicy }}
          command:
            - /bin/bash
            - -ec
            - |
              {{- include "wazuh.sysctlIfLess" (dict "key" "vm.max_map_count" "value" "262144") | nindent 14 }}
              {{- include "wazuh.sysctlIfLess" (dict "key" "fs.file-max" "value" "65536") | nindent 14 }}
          securityContext:
            privileged: true
            runAsUser: 0
          {{- with .Values.indexer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      volumes:
      - name: admin-certs
        secret:
          secretName: admin-tls
      - name: node-certs
        secret:
          secretName: node-tls
      - configMap:
          name: {{ include "wazuh.indexer.fullname" . }}-indexer-config
        name: indexer-conf
      containers:
        - name: wazuh-indexer
          {{- with .Values.indexer.extraSpec.container }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          imagePullPolicy: {{ .Values.indexer.images.pullPolicy }}
          image: "{{ .Values.indexer.images.repository }}:{{ .Values.indexer.images.tag }}"
          envFrom:
            - secretRef:
                name: {{ .Values.indexer.cred.existingSecret | default "indexer-cred" }}
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: {{ .Values.indexer.env.OPENSEARCH_JAVA_OPTS | quote }}
            - name: CLUSTER_NAME
              value: {{ .Values.indexer.env.CLUSTER_NAME | quote }}
            - name: NETWORK_HOST
              value: {{ .Values.indexer.env.NETWORK_HOST | quote }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DISCOVERY_SERVICE
              value: {{ include "wazuh.indexer.fullname" . }}-indexer-rest
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: {{ .Values.indexer.env.DISABLE_INSTALL_DEMO_CONFIG | quote }}
          {{- with .Values.indexer.additionalEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.indexer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.indexer.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.indexer.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            # PVC
            - mountPath: /var/lib/wazuh-indexer
              name: wazuh-indexer
            # Certs
            - mountPath: /usr/share/wazuh-indexer/certs/node-key.pem
              name: node-certs
              readOnly: true
              subPath: tls.key
            - mountPath: /usr/share/wazuh-indexer/certs/node.pem
              name: node-certs
              readOnly: true
              subPath: tls.crt
            - mountPath: /usr/share/wazuh-indexer/certs/root-ca.pem
              name: node-certs
              readOnly: true
              subPath: ca.crt
            - mountPath: /usr/share/wazuh-indexer/certs/admin.pem
              name: admin-certs
              readOnly: true
              subPath: tls.crt
            - mountPath: /usr/share/wazuh-indexer/certs/admin-key.pem
              name: admin-certs
              readOnly: true
              subPath: tls.key
            # Config
            - name: indexer-conf
              mountPath: /usr/share/wazuh-indexer/opensearch.yml
              subPath: opensearch.yml
              readOnly: true
            - name: indexer-conf
              mountPath: /usr/share/wazuh-indexer/opensearch-security/internal_users.yml
              subPath: internal_users.yml
              readOnly: true
            - name: indexer-conf
              mountPath: /usr/share/wazuh-indexer/opensearch-security/roles.yml
              subPath: roles.yml
              readOnly: true
            - name: indexer-conf
              mountPath: /usr/share/wazuh-indexer/opensearch-security/roles_mapping.yml
              subPath: roles_mapping.yml
              readOnly: true
            - name: indexer-conf
              mountPath: /usr/share/wazuh-indexer/opensearch-security/config.yml
              subPath: config.yml
              readOnly: true
          ports:
            - containerPort: {{ .Values.indexer.service.httpPort }}
              name: indexer-rest
            - containerPort: {{ .Values.indexer.service.nodes }}
              name: indexer-nodes
  volumeClaimTemplates:
    - metadata:
        name: wazuh-indexer
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.indexer.storageSize }}
        {{- $storageClass := .Values.indexer.storageClass }}
        {{- if $storageClass }}
        {{- if (eq "-" $storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ $storageClass }}
        {{- end }}
        {{- end }}
{{- end }}
