{{- if .Values.wazuh.worker.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "wazuh.fullname" . }}-manager-worker
spec:
  podSelector:
    matchLabels:
      app: {{ include "wazuh.fullname" . }}-manager
      node-type: worker
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.wazuh.worker.service.ports.agentEvents }}
    - ports:
        - protocol: TCP
          port: {{ .Values.wazuh.service.port }}
      from:
        - podSelector:
            matchLabels:
              app: {{ include "wazuh.fullname" . }}-manager
  egress:
    # Wazuh CTI (Cyber Threat Intelligence)
    - ports:
        - protocol: TCP
          port: 443
    - ports:
        - protocol: TCP
          port: {{ .Values.indexer.service.httpPort }}
      to:
        - podSelector:
            matchLabels:
              app: {{ include "wazuh.indexer.fullname" . }}-indexer
    - ports:
        - protocol: TCP
          port: {{ .Values.wazuh.service.port }}
      to:
        - podSelector:
            matchLabels:
              app: {{ include "wazuh.fullname" . }}-manager
              node-type: master
    - ports:
        - protocol: UDP
          port: 53
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
{{- end -}}
